config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/about'   => 'home#about'
  get '/feed'    => 'home#feed'
  get '/profile' => 'home#profile'

  devise_for :corporates, controllers: {
    registrations: "corporates/registrations",
    sessions: "corporates/sessions"
  }

  devise_for :individuals, controllers: {
    registrations: "individuals/registrations",
    sessions: "individuals/sessions"
  }

  resource :connect do
    resource :confirm
  end

  resources :publications

  resources :payments
end

app/views/shared/_edit_password.html.erb
<h2>Смена пароля</h2>

<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :put }) do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :reset_password_token %>

  <div class="field">
    <%= f.label :password, "Новый пароль" %><br />
    <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em><br />
    <% end %>
    <%= f.password_field :password, autofocus: true, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, "Подтвердите пароль" %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Сменить пароль" %>
  </div>
<% end %>

<%= render "shared/links" %>

app/views/shared/_footer.html.erb
<!--
==================================================
Footer Section Start
================================================== -->
<footer id="footer">
    <div class="container">
        <div class="col-md-8">
            <p class="copyright">&#169; <span>2017 Media Content Connection</span> . Все права принадлежат команде John Doe.</p>
        </div>
        <div class="col-md-4">
            <!-- Social Media -->
            <ul class="social">
                <li>
                    <a href="//fb.com/conconmedia" class="Facebook" target="_blank">
                        <i class="ion-social-facebook"></i>
                    </a>
                </li>
                <li>
                    <a href="//twitter.com/" class="Twitter" target="_blank">
                        <i class="ion-social-twitter"></i>
                    </a>
                </li>
                <li>
                    <a href="//linkedin.com/" class="Linkedin" target="_blank">
                        <i class="ion-social-linkedin"></i>
                    </a>
                </li>
                <li>
                    <a href="//plus.google.com/" class="Google Plus" target="_blank">
                        <i class="ion-social-googleplus"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</footer>
<!-- /#footer -->

app/views/shared/_header.html.erb
<!--
==================================================
Header Section Start
================================================== -->
<header id="top-bar" class="navbar-fixed-top animated-header">
    <div class="container">
        <div class="navbar-header">
            <!-- responsive nav button -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Навигация по сайту</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <!-- /responsive nav button -->
            
            <!-- logo -->
            <div class="navbar-brand">
                <a href="<%= root_url %>" >
                    <img src="<%= image_path 'logo.png' %>" alt="Логотип Con-Con">
                </a>
            </div>
            <!-- /logo -->
        </div>
        <!-- main menu -->
        <nav class="collapse navbar-collapse navbar-right" role="navigation">
            <div class="main-menu">
                <ul class="nav navbar-nav navbar-right">
                <% if individual_signed_in? %>
                    <li><a href="<%= feed_path %>" >Контент</a></li>
                    <li><a href="<%= profile_path %>" >Мой профиль</a></li>
                    <li><%= link_to 'Выйти', destroy_individual_session_path, method: 'delete' %></li>
                <% else %>
                    <li><a href="<%= root_url %>" >Главная</a></li>
                    <li><a href="<%= about_path %>">О проекте</a></li>
                <% end %>
                </ul>
            </div>
        </nav>
        <!-- /main nav -->
    </div>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Войти", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Зарегистрироваться", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Восстановить пароль", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Не получили письмо с подтверждением?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Не получили инструкции по восстановлению пароля?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/shared/_new_confirmation.html.erb
<h2>Отправить подтверждение повторно</h2>

<%= form_for(resource, as: resource_name, url: confirmation_path(resource_name), html: { method: :post }) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label 'Электронный адрес' %><br />
    <%= f.email_field :email, autofocus: true, value: (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email) %>
  </div>

  <div class="actions">
    <%= f.submit "Отправить" %>
  </div>
<% end %>

<%= render "shared/links" %>

app/views/shared/_payment_form.html.erb
<%= form_tag payments_path(publication: publication.id) do %>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>"
          data-amount="<%= publication.price_in_cents %>"
          data-name="<%= publication.title %>"
          data-description="<%= "#{publication.author.first_name} #{publication.author.last_name}" %>"
          data-locale="auto"
          data-email="<%= current_individual.email %>"
          data-panel-label="Оплатить"
          data-allow-remember-me="false"></script>
<% end %>

app/views/shared/_publication.html.erb
<article class="wow fadeInDown" data-wow-delay=".3s" data-wow-duration="500ms">
    <div class="blog-post-image">
        <a href="<%= publication_path(publication.id) %>"><img class="img-responsive" src="<%= image_path 'blog/post-1.jpg'%>" alt="" /></a>
    </div>
    <div class="blog-content">
        <h2 class="blogpost-title">
        <a href="<%= publication_path(publication.id) %>"><%= publication.title %></a>
        </h2>
        <div class="blog-meta">
            <span id="publication-date"><%= publication.created_at %></span>
            <span>автор 
                <%= "#{publication.author.first_name} #{publication.author.last_name}"%>
            </span>
        </div>
        <a href="<%= publication_path(publication.id)%>" class="btn btn-dafault btn-details">Читать подробнее</a>
        <% if !publication.sold? && publication.author.id != current_individual.id %>
          <div style="float:right;margin-top:20px"><%= render 'shared/payment_form', { publication: publication } %></div>
        <% end %>
    </div>
</article>

app/views/shared/_resend_confirmation.html.erb
<h2>Отправить инструкцию по восстановлению пароля повторно</h2>

<%= form_for(resource, as: resource_name, url: unlock_path(resource_name), html: { method: :post }) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email, "Электронная почта" %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Отправить инструкцию повторно" %>
  </div>
<% end %>

<%= render "shared/links" %>

app/views/shared/_restore_password.html.erb
<h2>Восстановить пароль</h2>

<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email, "Электронная почта" %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Выслать инструкцию по восстановлению" %>
  </div>
<% end %>

<%= render "shared/links" %>

app/views/shared/_title.html.erb
<!-- 
================================================== 
    Global Page Section Start
================================================== -->
<section class="global-page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h2><%= @title %></h2>
                </div>
            </div>
        </div>
    </div>
</section>