config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/about'   => 'home#about'
  get '/feed'    => 'home#feed'
  get '/profile' => 'home#profile'

  devise_for :corporates, controllers: {
    registrations: "corporates/registrations",
    sessions: "corporates/sessions"
  }

  devise_for :individuals, controllers: {
    registrations: "individuals/registrations",
    sessions: "individuals/sessions"
  }

  resource :connect do
    resource :confirm
  end

  resources :publications

  resources :payments
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :protect_content, only: [:feed, :profile]

  def index
  end

  def about
    @title = 'О проекте'
  end

  def feed
    @title = 'Последние публикации'

    publications = Publication.not_sold.order(created_at: 'desc')

    render locals: { publications: publications }
  end

  def profile
    @title = 'Личный профиль'

    if current_individual.can_sell?
      publications = current_individual.publications.not_sold.order(created_at: 'desc')
      sold_publications = current_individual.publications.sold.order(created_at: 'desc')
    else
      publications = current_individual.bought_publications
    end

    render locals: { publications: publications, sold_publications: sold_publications }
  end
end

app/views/home/about.html.erb
<%= render 'shared/title' %>

<!-- 
================================================== 
    Company Description Section Start
================================================== -->
<section class="company-description">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="block">
                    <p>Публикуйте свой контент<hr></p>
                    <p  class="wow fadeInUp" data-wow-delay=".5s" data-wow-duration="500ms">
                        Воспользуйтесь возможностью получить комментарии к своей работе от редакторов сообщества con-con.me и улучшайте свой контент
                    </p><hr>
                    <p>Зарабатывайте деньги на продаже своих публикаций</p><hr>
                    <p>Получите возможность публиковать свои материалы в открытом доступе</p>    
                </div>
            </div>
        </div>
    </div>
</section>


<!-- 
================================================== 
    Company Feature Section Start
================================================== -->
<section class="about-feature clearfix">
    <div class="container-fluid">
        <div class="row">
            <div class="block about-feature-1 wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".3s">
                <h2>
                    Статьи
                </h2>
                <p>
                    В два счета публикуйте свои статьи, блоги, репортажи на любую тематику, будьте услышаны
                </p>
            </div>
            <div class="block about-feature-2 wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".7s">
                <h2 class="item_title">
                    Фотографии
                </h2>
                <p>
                    С нашей платформой найти покупателя к вашему фото-контенту стало намного проще
                </p>
            </div>
        </div>
    </div>
</section>


<!-- 
================================================== 
    Team Section Start
================================================== -->
<section id="team">
    <div class="container">
        <div class="row">
            <h2 class="subtitle text-center">Нас поддерживают</h2>
            <div class="col-md-4">
                <div class="team-member wow fadeInLeft" data-wow-duration="500ms" data-wow-delay=".3s">
                    <div class="team-img">
                        <img src="<%= image_path 'team/team-1.jpg' %>" class="team-pic" alt="">
                    </div>
                    <h3 class="team_name">Майя Абдылдаева</h3>
                    <p class="team_designation">Блоггер</p>
                    <p class="team_text">Человек не равнодушный к социальным проблемам, пытающийся передать свою точку зрения через исследования разных сфер. Аналитик, ищущий компромиссы в спорных ситуациях и придерживающийся святой истины- у медали две стороны</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="team-member wow fadeInLeft" data-wow-duration="500ms" data-wow-delay=".3s">
                    <div class="team-img">
                        <img src="<%= image_path 'team/team-2.jpg' %>" class="team-pic" alt="">
                    </div>
                    <h3 class="team_name">Азиза Мурзашова</h3>
                    <p class="team_designation">PR</p>
                    <p class="team_text">Блогер, люблю горы, бег, эксперименты и путешествия</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="team-member wow fadeInLeft" data-wow-duration="500ms" data-wow-delay=".3s">
                    <div class="team-img">
                        <img src="<%= image_path 'team/team-3.jpg' %>" class="team-pic" alt="">
                    </div>
                    <h3 class="team_name">Елена Воронина</h3>
                    <p class="team_designation">Редактор портала</p>
                    <p class="team_text">Медиа-эксперт, тренер, PR</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--
==================================================
Clients Section Start
================================================== -->

app/views/home/feed.html.erb
<%= render 'shared/title' %>

<!--
==================================================
Global Page Section Start
================================================== -->
<section id="blog-full-width">
<div class="container">
<div class="row">
    <div class="col-md-4">
        <div class="sidebar">
            </div>
        </div>
        <div class="col-md-12">
            <%= render partial: 'shared/publication', collection: publications %>
        </div>
    </div>
</section>
<!--
==================================================
Call To Action Section Start
================================================== -->

app/views/home/index.html.erb
<!--
==================================================
Slider Section Start
================================================== -->
<section id="hero-area" >
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <div class="block wow fadeInUp" data-wow-delay=".3s">
                
                <!-- Slider -->
                <section class="cd-intro">
                    <h1 class="wow fadeInUp animated cd-headline slide" data-wow-delay=".4s" >
                    <!-- <span></span><br> -->
                    <span class="cd-words-wrapper">
                        <b class="is-visible">Платформа</b>
                        <b>Гражданской</b>
                        <b>Журналистики</b>
                    </span>
                    </h1>
                    </section> <!-- cd-intro -->
                    <!-- /.slider -->
                    <h2 class="wow fadeInUp animated" data-wow-delay=".6s" >
                        Публикуй - Продавай - Развивайся
                    </h2>
                    <% unless individual_signed_in? %>
                    <a class="btn-lines dark light wow fadeInUp animated smooth-scroll btn btn-default btn-green" data-wow-delay=".9s" href="<%= new_individual_session_path %>">Войти</a>
                    <a class="btn-lines dark light wow fadeInUp animated smooth-scroll btn btn-default btn-green" data-wow-delay=".9s" href="<%= new_individual_registration_path %>">Создать аккаунт</a>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/#main-slider-->

app/views/home/profile.html.erb
<%= render 'shared/title' %>

<section id="blog-full-width">
<div class="container">
<div class="row">
    <div class="col-md-4">
        <div class="sidebar">
            <div class="author widget">
                <img class="img-responsive" src="<%= image_path 'author/author-bg.jpg' %>">
                <div class="author-body text-center">
                    <div class="author-img">
                        <%= image_tag @current_individual.image.url(:medium) %>
                    </div>
                    <div class="author-bio">
                        <h3><%= "#{current_individual.first_name} #{current_individual.last_name}" %></h3>
                        <p><strong>Род деятельности:</strong> <%= current_individual.major %></p>
                        <p><strong>О себе:</strong> <%= current_individual.about %></p>
                    </div>
                    <% if current_individual.can_sell? %>
                      <div class="blog-content">
                        <%= link_to 'Опубликовать статью', new_publication_path, class: 'btn btn-dafault btn-details' %>
                      </div>
                    <% end %>
                </div>
            </div>
            <% if current_individual.can_sell? %>
            <div class="categories widget">
                <h3 class="widget-head">Статус работ</h3>
                <ul>
                    <li>
                        <a href="" id="activeButton" onclick="event.preventDefault()">Активные</a> <span class="badge"><%= publications.count %></span>
                    </li>
                    <li>
                        <a href="" id="soldButton" onclick="event.preventDefault()">Проданные</a> <span class="badge"><%= sold_publications.count %></span>
                    </li>
                </ul>
            </div>
            <% end %>
        </div>
        </div>
        <div class="col-md-8">
            <br><br>
            <% if current_individual.can_sell? %>
              <h1>Мои статьи</h1>
              <% if !publications.any? %>
                Вы еще не добавили ни одной статьи. Нажмите на кнопку "Опубликовать статью" для того, чтобы приступить.
              <% end %>
            <% else %>
              <h1>Купленные статьи</h1>
              <% if !publications.any? %>
                Вы еще не купили ни одной статьи. Перейдите в <a href="<%= feed_path %>">каталог</a>, для того, чтобы начать.
              <% end %>
            <% end %>
            <%= render partial: 'shared/publication', collection: publications %>
        </div>
    </div>
</section>